---
title: "Creating a draft Watershed Assessment Report"
author: "Carl Schwarz"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Version <- '2017-05-05'
```

## Introduction

A draft watershed assessment report will be created in MSWord using data extracted from the FWIS database.
This draft report can then be edited by tweaking the R code (preferred) or tweaking the MSWord document (but your
changes will be lost when you update the report).

This draft report is created using _R_ to do some computations, calling _JAGS_  (a program that does Bayesian computatons) from _R_
to compute the probability of belonging to the FSI categories, and _RMarkdown_ to mingle text and graphics into a MSWord document.

This follows the principle of Reproducible Research, where a single document contains ALL of the code used to analyze the data and
creates a report based on this. It is hoped that when each Watershed Assessment is updated, it will be necessary only to rerun the
code and do some minor teaks to the report.

## Getting your computer ready
Your computer will need the following software. Instructions for installing the software can be found
at <http://people.stat.sfu.ca/~cschwarz/CourseNotes/HowGetSoftware.html>.

* _R_. This is the statsitical software used to run the code. Don't forget to install the packages (add ons for _R_) as listed
in item (6) of the installation instructions in the above link. You will also need to install the following packages:
    + _stringr_ specialized functions for text processing
    + _R2Jags_, _coda_, _digest_ needed to run JAGS
    +  _pander_  needed to create tables in _RMarkdown_ 
    + _ggmaps_ needed to extract Google maps over the web. You will needs the most recent version which has NOT yet been released 
      to CRAN. You need to install it using 
        - devtools::install_github("dkahle/ggmap") 
     on the R console. This may require the _devtools_ package to also be installed.

* _RStudio_. An integrated development environment that controls _R_ and its output.

* _JAGS_ (Just Another Gibbs Sampler). A cross-platform program that performs Bayesian computations. This program will be called by _R_.
Don't forget to install the additional _R_ packages listed under item (2) of the _JAGS_ installation instructions in the above link namely:
    + _R2Jags_, _coda_, and _digest_ needed to run JAGS

* _JAVA_. In order to read the FWIS files directly you will have to authorize _JAVA_ programs on your computer.


## Getting the FWIS data
Information on each watershed is extracted from the FWIS database. Contact ????? for further details.

The current extraction program created Excel 95 files. _R_ required Excel 97 or later, so you will have to open and save
the file in Excel 97 or later format.


## Create a working directly.
Create a working directory with the FWIS data file. This directory will also include the _RMarkdown_ files used to create the draft
watershed report.

## Copy the _RMarkdown_ template files to the working directory.
The template files are located on the  _GitHub_ server


- download from GitHub
- create clones for species not present



### Editing the template files
- reproducible results
- changing plots
- selecting species to measure
- editing the data
- editing the map


