%  Watershed Report Template
% Satisfaction plot2 has colors reversed for Above Average and Excellend

<<DefineFunctions, include=FALSE>>=
sanitizeLatexS <- function(str) {
    str <- gsub('([#$%&~_\\^\\\\{}])', '\\\\\\1', str, perl = TRUE);
    str <- iconv(str, to="ASCII", sub=" ")
    str
}
@
\documentclass[]{article} % two column might work, but table placement needs help

\usepackage{caption} % allows line breaks in table captions
\usepackage{multicol}
\usepackage{caption}
\captionsetup[figure]{font=small,skip=-10pt} % reduce space between caption and figure
%\captionsetup[table]{font=small,skip=0pt}
\usepackage[top=1.0in, bottom=1.0in, left=1.0in, right=1.00in]{geometry}

\usepackage{comment}

\usepackage{titlesec} % set spacing after section command (left, before, after)
\titlespacing\section{0pt}{4pt plus 2pt minus 2pt}{4pt plus 2pt minus 2pt}

\newcommand\percent{\%}

\usepackage{float} % to allow to force non-floating

\newlength{\storeparskip}
\setlength{\storeparskip}{\parskip}% Store \parskip
\setlength{\parskip}{\baselineskip} % space between paragraphs


\usepackage{url}  % to include URLS i the document

\begin{document}


% This generates the individual watershed reports


% Get the watershed data from the brewing function
 



\newcommand{\mylarge}{\fontsize{16}{20}\selectfont}
\newcommand{\myLarge}{\fontsize{36}{50}\selectfont}
\newcommand{\myLARGE}{\fontsize{43}{54}\selectfont}


\title{\Sexpr{ws.data$Watershed[1]} - Summary of Watershed Level Fish Population Assessment}
\date{}



\maketitle

\setcounter{secnumdepth}{0} % don't numbersections

\setcounter{tocdepth}{2}
{\setlength{\parskip}{\storeparskip}% Restore \parskip within this scope so TOC isn't double spaced
\tableofcontents
}
\clearpage



\section{Background}

``How are the fish in my river and streams doing?''
We need this answer to set appropriate fishing regulations, 
to understand and correct any problems with fish habitat and 
to guard against invasive species.  
A healthy fish population and fish community means we 
can all enjoy the benefits of sustainable fisheries 
and healthy ecosystems. 
A standard method of assessing the status of 
fish populations is necessary to allow comparisons of fish sustainability 
across the years in a watershed, and to compare to other 
watersheds in the province. 
In Alberta, we use accepted standard sampling methods for
watershed fisheries assessments. 
These methods provide the necessary data on fish abundance, 
biological data (such as genetic information, age and sex), 
and species diversity to assess sustainability over time and space.

\section{Watershed Assessments}
Alberta Environment and Parks monitor fish in flowing waters using 
standardized electrofishing and habitat surveys techniques. 
Surveys often occur during the summer when river and stream 
flows are lower to allow for safe working conditions and high 
visibility of observed fish.  Although information is collected 
from all species, assessments often focus on game species such as
Westslope Cutthroat Trout ({\it Oncorhynchus clarkii lewisi}), 
Bull Trout ({\it Salvelinus confluentus}), 
Arctic Grayling ({\it Thymallus arcticus}), 
Athabasca Rainbow Trout ({\it Oncorhynchus mykiss}), 
and Mountain Whitefish ({\it Prosopium williamsoni}).

Watersheds are defined by the Hydrologic Unit Code (HUC) 10 watershed boundary, 
as identified by the HUC Watersheds of Alberta system of classification system 
(reference? AB or USGS?). 
Within the study area, {\LARGE X - how will I know this from dataset?} potential sampling locations were randomly 
chosen using ArcGIS (ESRI, 2013) and R (R Core Team, 2015) 
using generalized random tessellation stratified (GRTS) 
sampling (Stevens and Olsen, 2004; Reilly, 2016). 
Sites were further removed from consideration if they were observed or 
strongly suspected to be dry or if there were access limitations that prevented crews from reaching the sites. 
In total, \Sexpr{length(unique(ws.data$Location..))} sites were sampled in the \Sexpr{ws.data$Watershed[1]} watershed 
({\LARGE Figure 1 - where can I get the map?}). 


Fin clips (adipose and/or upper caudal clip) were taken from Cutthroat Trout and Bull Trout, and stored in 95\% ethanol. 
Bull Trout tissue samples are stored at AEP’s Cochrane office. 
Cutthroat Trout tissue samples are analyzed to determine the extent 
of introgression with non-native Rainbow Trout. 
The estimated proportion of the genome that is introgressed is scored on a scale of 0 to 1; 
0 represents pure Rainbow Trout and  1 represents pure Westslope Cutthroat Trout. 
The genetic status of all fish field-identified as Cutthroat Trout 
was considered unknown, and is referred to in this report as Cutthroat Trout until the results of the genetic analysis are available and genetic status is assigned. 
Tissue samples collected from Cutthroat Trout captured in \Sexpr{ws.data$Watershed[1]}
were submitted to the Montana Conservation Genetics Laboratory 
at the University of Montana for analysis.

Basic summary statistics, bootstrap of mean catch rates, and the creation of graphs and figures were done using Microsoft Excel (Microsoft Corporation, 2010),  
R (R Core Team, 2015) , and JMP (SAS Institute Incorporated, 2016). 
Fitting of the Von Bertalanffy growth curve was conducted in Fishery Analysis Modeling Simulator (FAMS 1.0; Slipke 2010). 

Fish and habitat sampling protocols used for this study are described 
in the Standard for Sampling of Small Streams in Alberta 
(Alberta Fisheries Management Branch, 2013). 
Protocols were also informed by the Alberta Biodiversity Monitoring Institute Fish Survey Methods for Rivers (ABMI and ASRD, 2014), 
Fish Ageing Methods for Alberta (Mackay et al., 1990), 
Standard for Ageing Walleyes in Alberta (Watkins and Spencer, 2009), 
and Alberta’s Electrofishing Certification and Safety Standard (SRD, 2008). 
Sites were typically 300 metres in length.

How is this information used?
Catch rates (i.e., backpack electrofishing: number of fish per 300 meters, 
boat electrofishing: number of fish per 1 km) 
of fish species are an index of the populations' abundance, 
with higher catch rates meaning there are more fish in a stream or river. 
The sizes and age of fish also tell us if problems with overharvest 
(e.g. too few fish living to old age) or habitat (e.g., poor spawning success) 
are a concern. Biologists use this information, as well as a variety 
of data on water quality, access, development, and 
habitat threats as part of Alberta’s Fish Sustainability Index (FSI)
and evaluation of species recovery work. 

\section{Results}
Fish and habitat sampling was conducted at \Sexpr{length(unique{ws.data$Location..})}
sites within the \Sexpr{ws.data$Watershed[1]}
(HUC 0402070101) during [Month, day, 201X to Month, Day, 201X. This watershed is found approximately x km northwest from the city of Calgary.
X species of fish were captured and included:  X Bull Trout, X Cutthroat Trout, X Brown Trout, X Brook Trout, X Longnose Sucker,X Longnose Dace, X Spoonhead Sculpin and X Brook Stickleback. The mean size, size range and catch rates for all captured sportfish species are summarized in Table 2. 
Table 2. Summary sportfish size, size range and backpack electrofishing catch rates captured in the [insert watershed name] watershed in 201X. 
Species	Size
Mean, Range (mm)	Total Catch Rate
Fish / 300 m (95% CI)
Bull Trout	85, 61-340	0.70 (0 – 2.06)
Cutthroat Trout	173, 105-394	0.30 (0 – 0.60)
Brown Trout	226, 147-305	0.10 (0 - 0.31)
Brook Trout	121, 46-305	35.65 ( 53.5 – 17.79)

Subsections for each game species?
-describe the mean catch rate and describe risk category
-describe FL distribution
Cutthroat Trout

The mean catch rate of Cutthroat Trout in the [insert watershed name] in 201X was 0.30 fish / 300 m (95% CI 0 – 0.6). The catch rate of mature and immature Cutthroat Trout were 0.05 fish / 300 m (95% CI 0 - 0.15) and 0.25 fish / 300 m (95% CI 0 – 0.55), respectively. The catch rate for total Cutthroat Trout corresponds to the draft FSI Category of ‘Very High Risk’, with an FSI Score of 1 (Figure x).  

The length distribution shows variable recruitment, and very low catches of mature Cutthroat Trout (>150 mm) (Figure x)

 

Figure x. Posterior probability of belonging to each FSI category after a trendline is fit.

The length distribution shows [insert 1-2 sentences describing recruitment, and length distribution] (Figure x)

 
Figure X. Length distribution of Cutthroat Trout in the [insert watershed name, year]. Black vertical line indicates estimated length at 50% maturity (153 mm Fork Length).

Summary
-describe where fish are found in the watershed (general statement for all game fish species)
-For each game species interpret the catch rate and size distribution. What does this mean for the population? Did any environmental factors potentially influence assessment e.g. flood? What kind of conservation actions need to be taken?


\section{Literature}


\noindent Alberta Biodiversity Monitoring Institute and Alberta Sustainable Resource Development (ABMI and ASRD). 2014. 

\noindent Fish Survey Methods for Rivers: ABMI and ASRD Collaboration. 
Written by Jim Schiek and edited by M.G. Sullivan. 
Prepared for Alberta Biodiversity Monitoring Institute andAlberta Sustainable Resource Development. 20 pp.

\noindent Alberta Fisheries Management Branch. 2013. 
Standard for sampling of small streams in Alberta. 
Alberta  Environment and Sustainable Resource Development, Fisheries Management Standards 	Committee. 19 pp.

\noindent Environmental Systems Research Institute (ESRI). 2013. 
ArcGIS Desktop: Version 10.2. Redlands , CA: 
Environmental Systems Research Institute.

\noindent R Core Team. 2015. R: A language and environment for statistical computing. R Foundation forStatistical Computing, Vienna, Austria. URL \url{http://www.R-project.org/} .


\noindent Mackay, W.C., G.R.\ Ash, H.J.\ Norris. 1990. Fish ageing methods for Alberta. R.L.\ \& L. Environmental Services Ltd. In assoc. with Alberta Fish and Wildlife Division and University of Alberta, Edmonton. 113 pp.

\noindent Microsoft Corporation. 2010. Microsoft Excel, version 14.0.7145.5000.  
Part of Microsoft Office Professional Plus 2010. Redmond Washington.

\noindent Reilly, J. 2016. GRTS: User friendly method for busy biologists. 
Alberta Environment and Parks. 4 pp.

\noindent Statistical Analysis Software (SAS) Institute Inc. 2016. 
JMP Statistical Discovery, version 13.0.0. SAS 
Campus Drive, Cary, North Carolina	27513, USA.

\noindent Slipke, J.W. 2010. Fishery Analyses and Modeling Simulator (FAMS). Version 1.0.

\noindent Alberta Sustainable Resource Development (ASRD). 2008. 
Electrofishing Certification and Safety Standard. 
Alberta Sustainable Resource Development,	Fish and Wildlife Division. Edmonton, AB. 76 pp.

\noindent Stevens, D.L., A.R.\ Olsen. 2004. 
Spatially balanced sampling of natural resources. 
Journal of the American Statistical Association 99(465):262-278.

\noindent Watkins, O.B., S.C.\ Spencer. 2009. 
Collection, preparation and ageing of walleye otoliths. 
Alberta Sustainable Resource Development, Fish and Wildlife Division. 
Spruce Grove, AB. 26 pp.




\end{document}
# we need a blank line at the end (See Reproducible Research with R and Rstudio, page 247)

