%  Watershed Report Template
% Satisfaction plot2 has colors reversed for Above Average and Excellend


\documentclass[]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt} % two column might work, but table placement needs help

\usepackage{caption} % allows line breaks in table captions
\usepackage{multicol}
\usepackage{caption}
\captionsetup[figure]{font=small,skip=-10pt} % reduce space between caption and figure
%\captionsetup[table]{font=small,skip=0pt}
\usepackage[top=1.0in, bottom=1.0in, left=1.0in, right=1.00in]{geometry}

\usepackage{comment}

\usepackage{titlesec} % set spacing after section command (left, before, after)
\titlespacing\section{0pt}{4pt plus 2pt minus 2pt}{4pt plus 2pt minus 2pt}

\newcommand\percent{\%}

\usepackage{float} % to allow to force non-floating

\newlength{\storeparskip}
\setlength{\storeparskip}{\parskip}% Store \parskip
\setlength{\parskip}{\baselineskip} % space between paragraphs


\usepackage{url}  % to include URLS i the document
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


% This generates the individual watershed reports


% Get the watershed data from the brewing function
 



\newcommand{\mylarge}{\fontsize{16}{20}\selectfont}
\newcommand{\myLarge}{\fontsize{36}{50}\selectfont}
\newcommand{\myLARGE}{\fontsize{43}{54}\selectfont}


\title{Quirk Creek\\ Summary of Watershed Level Fish Population Assessment}
\date{}



\maketitle

%\setcounter{secnumdepth}{0} % don't numbersections

\setcounter{tocdepth}{2}
{\setlength{\parskip}{\storeparskip}% Restore \parskip within this scope so TOC isn't double spaced
\tableofcontents
}
\clearpage



\section{Background}
\noindent ``How are the fish in my river and streams doing?''
We need this answer to set appropriate fishing regulations, 
to understand and correct any problems with fish habitat and 
to guard against invasive species.  
A healthy fish population and fish community means we 
can all enjoy the benefits of sustainable fisheries 
and healthy ecosystems. 
A standard method of assessing the status of 
fish populations is necessary to allow comparisons of fish sustainability 
across the years in a watershed, and to compare to other 
watersheds in the province. 
In Alberta, we use accepted standard sampling methods for
watershed fisheries assessments. 
These methods provide the necessary data on fish abundance, 
biological data (such as genetic information, age and sex), 
and species diversity to assess sustainability over time and space.

\section{Watershed Assessments}
\noindent Alberta Environment and Parks monitor fish in flowing waters using 
standardized electrofishing and habitat surveys techniques. 
Surveys often occur during the summer when river and stream 
flows are lower to allow for safe working conditions and high 
visibility of observed fish.  Although information is collected 
from all species, assessments often focus on species such as
Westslope Cutthroat Trout ({\it Oncorhynchus clarkii lewisi}), 
Bull Trout ({\it Salvelinus confluentus}), 
Arctic Grayling ({\it Thymallus arcticus}), 
Athabasca Rainbow Trout ({\it Oncorhynchus mykiss}), 
and Mountain Whitefish ({\it Prosopium williamsoni}).

Watersheds are defined by the Hydrologic Unit Code (HUC) 10 watershed boundary, 
as identified by the HUC Watersheds of Alberta system of classification system 
(reference? AB or USGS?). 
Within the study area, {\LARGE X - how will I know this from dataset?} potential sampling locations were randomly 
chosen using ArcGIS (ESRI, 2013) and R (R Core Team, 2015) 
using generalized random tessellation stratified (GRTS) 
sampling (Stevens and Olsen, 2004; Reilly, 2016). 
Sites were further removed from consideration if they were observed or 
strongly suspected to be dry or if there were access limitations that prevented crews from reaching the sites. 
In total, 8 sites were sampled in the Quirk Creek watershed 
({\LARGE Figure 1 - where can I get the .kml files for the map?}). 

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/WatershetMap-1} 

\end{knitrout}
\end{center}
\caption{Histogram of campground recommendations for this campground}
\label{fig:recommendhist}
\end{figure}


{\Large Is this paragraph the same for ALL watersheds?}
Fin clips (adipose and/or upper caudal clip) were taken from Cutthroat Trout and Bull Trout, and stored in 95\% ethanol. 
Bull Trout tissue samples are stored at AEP’s Cochrane office. 
Cutthroat Trout tissue samples are analyzed to determine the extent 
of introgression with non-native Rainbow Trout. 
The estimated proportion of the genome that is introgressed is scored on a scale of 0 to 1; 
0 represents pure Rainbow Trout and  1 represents pure Westslope Cutthroat Trout. 
The genetic status of all fish field-identified as Cutthroat Trout 
was considered unknown, and is referred to in this report as Cutthroat Trout until the results of the genetic analysis are available and genetic status is assigned. 
Tissue samples collected from Cutthroat Trout captured in Quirk Creek
were submitted to the Montana Conservation Genetics Laboratory 
at the University of Montana for analysis.

Basic summary statistics, bootstrap of mean catch rates, 
and the creation of graphs and figures were done using Microsoft Excel (Microsoft Corporation, 2010),  
R (R Core Team, 2015) , and JMP (SAS Institute Incorporated, 2016). 
Fitting of the Von Bertalanffy growth curve was conducted in Fishery Analysis Modeling Simulator (FAMS 1.0; Slipke 2010). 

Fish and habitat sampling protocols used for this study are described 
in the Standard for Sampling of Small Streams in Alberta 
(Alberta Fisheries Management Branch, 2013). 
Protocols were also informed by the Alberta Biodiversity Monitoring Institute Fish Survey Methods for Rivers (ABMI and ASRD, 2014), 
Fish Ageing Methods for Alberta (Mackay et al., 1990), 
Standard for Ageing Walleyes in Alberta (Watkins and Spencer, 2009), 
and Alberta's Electrofishing Certification and Safety Standard (SRD, 2008). 
Sites were typically 300 metres in length.

How is this information used?
Catch rates (i.e., backpack electrofishing: number of fish per 300 meters, 
boat electrofishing: number of fish per 1 km) 
of fish species are an index of the populations' abundance, 
with higher catch rates meaning there are more fish in a stream or river. 
The sizes and age of fish also tell us if problems with overharvest 
(e.g. too few fish living to old age) or habitat (e.g., poor spawning success) 
are a concern. Biologists use this information, as well as a variety 
of data on water quality, access, development, and 
habitat threats as part of Alberta’s Fish Sustainability Index (FSI)
and evaluation of species recovery work. 

\section{Results}
\noindent Fish and habitat sampling was conducted at 8
sites within the Quirk Creek
(HUC 04021001) from 1987-08-27 to 2013-08-28.
This watershed is found approximately {\LARGE x - need a table} 
km northwest from the city of Calgary.

There were 4 species of fish were captured over this period and the mean fork length, 
size range, and mean catch rates for all captured fish over this period are summarized in Table~\ref{tab:fishsummary}.



\begin{table}[h]
\centering
\captionsetup{width=.9\linewidth}
\caption{Summary statistics on species of fish captured in Quirk Creek.}
\label{tab:fishsummary}
\begin{tabular}{| l | r r r r | } \hline
           &           &  Mean   &  Min     & Max     \\
Species    &           &  fork   &  fork    & fork    \\
Code       &   n       &  length &  length  & length  \\
           &           & mm      &  mm      &  mm     \\ \hline
BKTR  &  2912  &  127  &  37  &  327 \\ 
BLBK  &  138  &  139  &  82  &  312 \\ 
BLTR  &  246  &  188  &  90  &  495 \\ 
CTTR  &  1972  &  132  &  22  &  401 \\ 
\hline 

\end{tabular}
\end{table}

Catch per unit effort (CPUE) was computed for each species for each year as follows:
\begin{itemize}
\item The distance sampled (m) and count by species was extracted for each {\it Inventory Survey ID}.
\item The distance sampled and count by species were summed over multiple {\it Inventory Survey IDs} for a location.
A location was defined by the combination of TTM Easting and TTM Northing. 
\item The CPUE was computed as total count / total distance $\times$ 300 m to standardize to a per 300 m basis.
\end{itemize}
A Bayesian analysis was used to 
compute the posterior probability of belonging to each FWIS Category based on the yearly trend in the median CPUE
accounting for within-year sampling variation, site-to-site random variation, and year-specific effects (process error)
as described in Schwarz (2017).

% Computing the CPUE


In the following sections, a more detailed investigation of the status of each of the above species will be provided.




% Create a separate subsecton for each species of fish.
% Because the species of fish are now known in advance, we need to program all of the LaTeX ourselves


% This is the code for each separate species

\clearpage % new page for each species
\subsection{ BKTR}



The  mean fork length and size range for this species on a yearly basis are summarized in 
Table~\ref{tab:fishsummaryBKTR} 
and plotted in 
Figure~\ref{fig:fishsummaryBKTR}.

\begin{table}[h]
\centering
\captionsetup{width=.9\linewidth}
\caption{Summary statistics on fork length BKTR captured in Quirk Creek.}
\label{tab:fishsummaryBKTR}
\begin{tabular}{| l | r r r r | } \hline
           &           &  Mean   &  Min     & Max     \\
           &           &  fork   &  fork    & fork    \\
Year       &   n       &  length &  length  & length  \\
           &           & mm      &  mm      &  mm     \\ \hline
1987  &  61  &  205  &  104  &  327 \\ 
2000  &  30  &  184  &  78  &  235 \\ 
2006  &  1046  &  126  &  41  &  287 \\ 
2007  &  624  &  122  &  38  &  305 \\ 
2008  &  375  &  126  &  47  &  249 \\ 
2009  &  94  &  116  &  45  &  263 \\ 
2010  &  228  &  131  &  39  &  310 \\ 
2011  &  219  &  122  &  37  &  300 \\ 
2012  &  125  &  118  &  37  &  281 \\ 
2013  &  110  &  125  &  46  &  313 \\ 
\hline 

\end{tabular}
\end{table}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-8-1} 

\end{knitrout}
\end{center}
\caption{Changes in fork length for BKTR on Quirk Creek}
\label{fig:fishsummaryBKTR}
\end{figure}


\clearpage
The length distribution over all years is shown in Figure~\ref{fig:ldistBKTR}.
Black vertical line indicates estimated length at 50\% maturity (153 mm Fork Length).
{\Large Not yet shown --How is this known from the data? }


\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-9-1} 

\end{knitrout}
\end{center}
\caption{Fork length distribution for BKTR on Quirk Creek}
\label{fig:ldistBKTR}
\end{figure}


A plot of the CPUE over time is shown in Figure~\ref{fig:rawtrendBKTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-10-1} 

\end{knitrout}
\end{center}
\caption{Raw data for BKTR at Quirk Creek with FSI categories}
\label{fig:rawtrendBKTR}
\end{figure}




The Bayesian analysis on trend found that the median CPUE was changing at 
 0.79\% (SD  8.18\%) per year
and the posterior probability that the slope is positive is  0.56.

Plots of the posterior distribution of the trend line for the median and the FWSI Category membership are shown in 
Figure~\ref{fig:postplotBKTR} and
Figure~\ref{fig:fsiplotBKTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-12-1} 

\end{knitrout}
\end{center}
\caption{Posterior plot of trend in medain BKTR at Quirk Creek}
\label{fig:postplotBKTR}
\end{figure}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-13-1} 

\end{knitrout}
\end{center}
\caption{Posterior probability of membership in FWSI category for  BKTR at Quirk Creek}
\label{fig:fsiplotBKTR}
\end{figure}





% This is the code for each separate species

\clearpage % new page for each species
\subsection{ BLTR}



The  mean fork length and size range for this species on a yearly basis are summarized in 
Table~\ref{tab:fishsummaryBLTR} 
and plotted in 
Figure~\ref{fig:fishsummaryBLTR}.

\begin{table}[h]
\centering
\captionsetup{width=.9\linewidth}
\caption{Summary statistics on fork length BLTR captured in Quirk Creek.}
\label{tab:fishsummaryBLTR}
\begin{tabular}{| l | r r r r | } \hline
           &           &  Mean   &  Min     & Max     \\
           &           &  fork   &  fork    & fork    \\
Year       &   n       &  length &  length  & length  \\
           &           & mm      &  mm      &  mm     \\ \hline
1987  &  18  &  181  &  99  &  248 \\ 
2000  &  1  &  NA  &  NA  &  NA \\ 
2006  &  75  &  204  &  136  &  273 \\ 
2007  &  81  &  177  &  97  &  298 \\ 
2008  &  31  &  202  &  134  &  277 \\ 
2009  &  2  &  131  &  130  &  132 \\ 
2010  &  4  &  189  &  154  &  231 \\ 
2011  &  5  &  193  &  115  &  294 \\ 
2012  &  17  &  139  &  103  &  259 \\ 
2013  &  12  &  216  &  90  &  495 \\ 
\hline 

\end{tabular}
\end{table}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-16-1} 

\end{knitrout}
\end{center}
\caption{Changes in fork length for BLTR on Quirk Creek}
\label{fig:fishsummaryBLTR}
\end{figure}


\clearpage
The length distribution over all years is shown in Figure~\ref{fig:ldistBLTR}.
Black vertical line indicates estimated length at 50\% maturity (153 mm Fork Length).
{\Large Not yet shown --How is this known from the data? }


\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-17-1} 

\end{knitrout}
\end{center}
\caption{Fork length distribution for BLTR on Quirk Creek}
\label{fig:ldistBLTR}
\end{figure}


A plot of the CPUE over time is shown in Figure~\ref{fig:rawtrendBLTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-18-1} 

\end{knitrout}
\end{center}
\caption{Raw data for BLTR at Quirk Creek with FSI categories}
\label{fig:rawtrendBLTR}
\end{figure}




The Bayesian analysis on trend found that the median CPUE was changing at 
 1.05\% (SD  8.90\%) per year
and the posterior probability that the slope is positive is  0.54.

Plots of the posterior distribution of the trend line for the median and the FWSI Category membership are shown in 
Figure~\ref{fig:postplotBLTR} and
Figure~\ref{fig:fsiplotBLTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-20-1} 

\end{knitrout}
\end{center}
\caption{Posterior plot of trend in medain BLTR at Quirk Creek}
\label{fig:postplotBLTR}
\end{figure}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-21-1} 

\end{knitrout}
\end{center}
\caption{Posterior probability of membership in FWSI category for  BLTR at Quirk Creek}
\label{fig:fsiplotBLTR}
\end{figure}





% This is the code for each separate species

\clearpage % new page for each species
\subsection{ BLBK}



The  mean fork length and size range for this species on a yearly basis are summarized in 
Table~\ref{tab:fishsummaryBLBK} 
and plotted in 
Figure~\ref{fig:fishsummaryBLBK}.

\begin{table}[h]
\centering
\captionsetup{width=.9\linewidth}
\caption{Summary statistics on fork length BLBK captured in Quirk Creek.}
\label{tab:fishsummaryBLBK}
\begin{tabular}{| l | r r r r | } \hline
           &           &  Mean   &  Min     & Max     \\
           &           &  fork   &  fork    & fork    \\
Year       &   n       &  length &  length  & length  \\
           &           & mm      &  mm      &  mm     \\ \hline
2000  &  4  &  228  &  206  &  247 \\ 
2006  &  103  &  127  &  82  &  312 \\ 
2007  &  23  &  171  &  105  &  249 \\ 
2008  &  2  &  236  &  226  &  246 \\ 
2011  &  2  &  96  &  90  &  101 \\ 
2013  &  4  &  156  &  136  &  181 \\ 
\hline 

\end{tabular}
\end{table}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-24-1} 

\end{knitrout}
\end{center}
\caption{Changes in fork length for BLBK on Quirk Creek}
\label{fig:fishsummaryBLBK}
\end{figure}


\clearpage
The length distribution over all years is shown in Figure~\ref{fig:ldistBLBK}.
Black vertical line indicates estimated length at 50\% maturity (153 mm Fork Length).
{\Large Not yet shown --How is this known from the data? }


\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-25-1} 

\end{knitrout}
\end{center}
\caption{Fork length distribution for BLBK on Quirk Creek}
\label{fig:ldistBLBK}
\end{figure}


A plot of the CPUE over time is shown in Figure~\ref{fig:rawtrendBLBK}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-26-1} 

\end{knitrout}
\end{center}
\caption{Raw data for BLBK at Quirk Creek with FSI categories}
\label{fig:rawtrendBLBK}
\end{figure}




The Bayesian analysis on trend found that the median CPUE was changing at 
-21.52\% (SD 18.77\%) per year
and the posterior probability that the slope is positive is  0.10.

Plots of the posterior distribution of the trend line for the median and the FWSI Category membership are shown in 
Figure~\ref{fig:postplotBLBK} and
Figure~\ref{fig:fsiplotBLBK}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-28-1} 

\end{knitrout}
\end{center}
\caption{Posterior plot of trend in medain BLBK at Quirk Creek}
\label{fig:postplotBLBK}
\end{figure}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-29-1} 

\end{knitrout}
\end{center}
\caption{Posterior probability of membership in FWSI category for  BLBK at Quirk Creek}
\label{fig:fsiplotBLBK}
\end{figure}





% This is the code for each separate species

\clearpage % new page for each species
\subsection{ CTTR}



The  mean fork length and size range for this species on a yearly basis are summarized in 
Table~\ref{tab:fishsummaryCTTR} 
and plotted in 
Figure~\ref{fig:fishsummaryCTTR}.

\begin{table}[h]
\centering
\captionsetup{width=.9\linewidth}
\caption{Summary statistics on fork length CTTR captured in Quirk Creek.}
\label{tab:fishsummaryCTTR}
\begin{tabular}{| l | r r r r | } \hline
           &           &  Mean   &  Min     & Max     \\
           &           &  fork   &  fork    & fork    \\
Year       &   n       &  length &  length  & length  \\
           &           & mm      &  mm      &  mm     \\ \hline
1987  &  117  &  159  &  75  &  292 \\ 
1988  &  7  &  215  &  145  &  278 \\ 
2000  &  3  &  153  &  110  &  196 \\ 
2006  &  418  &  167  &  28  &  390 \\ 
2007  &  371  &  122  &  26  &  395 \\ 
2008  &  335  &  130  &  30  &  401 \\ 
2009  &  161  &  99  &  30  &  378 \\ 
2010  &  157  &  115  &  31  &  320 \\ 
2011  &  220  &  119  &  23  &  356 \\ 
2012  &  107  &  101  &  22  &  351 \\ 
2013  &  76  &  134  &  30  &  373 \\ 
\hline 

\end{tabular}
\end{table}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-32-1} 

\end{knitrout}
\end{center}
\caption{Changes in fork length for CTTR on Quirk Creek}
\label{fig:fishsummaryCTTR}
\end{figure}


\clearpage
The length distribution over all years is shown in Figure~\ref{fig:ldistCTTR}.
Black vertical line indicates estimated length at 50\% maturity (153 mm Fork Length).
{\Large Not yet shown --How is this known from the data? }


\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-33-1} 

\end{knitrout}
\end{center}
\caption{Fork length distribution for CTTR on Quirk Creek}
\label{fig:ldistCTTR}
\end{figure}


A plot of the CPUE over time is shown in Figure~\ref{fig:rawtrendCTTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-34-1} 

\end{knitrout}
\end{center}
\caption{Raw data for CTTR at Quirk Creek with FSI categories}
\label{fig:rawtrendCTTR}
\end{figure}




The Bayesian analysis on trend found that the median CPUE was changing at 
14.47\% (SD  8.95\%) per year
and the posterior probability that the slope is positive is  0.96.

Plots of the posterior distribution of the trend line for the median and the FWSI Category membership are shown in 
Figure~\ref{fig:postplotCTTR} and
Figure~\ref{fig:fsiplotCTTR}.

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-36-1} 

\end{knitrout}
\end{center}
\caption{Posterior plot of trend in medain CTTR at Quirk Creek}
\label{fig:postplotCTTR}
\end{figure}

\begin{figure}[h]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-37-1} 

\end{knitrout}
\end{center}
\caption{Posterior probability of membership in FWSI category for  CTTR at Quirk Creek}
\label{fig:fsiplotCTTR}
\end{figure}





\clearpage
\section{Summary}
-describe where fish are found in the watershed (general statement for all game fish species) {\Large from where will this text come from?}


-For each game species interpret the catch rate and size distribution. What does this mean for the population? Did any environmental factors potentially influence assessment e.g. flood? What kind of conservation actions need to be taken? {\Large from where will this text come from?}

\clearpage
\section{References}


\noindent Alberta Biodiversity Monitoring Institute and Alberta Sustainable Resource Development (ABMI and ASRD). 2014. 

\noindent Fish Survey Methods for Rivers: ABMI and ASRD Collaboration. 
Written by Jim Schiek and edited by M.G. Sullivan. 
Prepared for Alberta Biodiversity Monitoring Institute andAlberta Sustainable Resource Development. 20 pp.

\noindent Alberta Fisheries Management Branch. 2013. 
Standard for sampling of small streams in Alberta. 
Alberta  Environment and Sustainable Resource Development, Fisheries Management Standards 	Committee. 19 pp.

\noindent Environmental Systems Research Institute (ESRI). 2013. 
ArcGIS Desktop: Version 10.2. Redlands , CA: 
Environmental Systems Research Institute.

\noindent R Core Team. 2015. R: A language and environment for statistical computing. R Foundation forStatistical Computing, Vienna, Austria. URL \url{http://www.R-project.org/} .


\noindent Mackay, W.C., G.R.\ Ash, H.J.\ Norris. 1990. Fish ageing methods for Alberta. R.L.\ \& L. Environmental Services Ltd. In assoc. with Alberta Fish and Wildlife Division and University of Alberta, Edmonton. 113 pp.

\noindent Microsoft Corporation. 2010. Microsoft Excel, version 14.0.7145.5000.  
Part of Microsoft Office Professional Plus 2010. Redmond Washington.

\noindent Reilly, J. 2016. GRTS: User friendly method for busy biologists. 
Alberta Environment and Parks. 4 pp.

\noindent Schwarz, C.J. 2017. Bayesian classification into the Alberta FWIS Categories.
Unpublished report.

\noindent Statistical Analysis Software (SAS) Institute Inc. 2016. 
JMP Statistical Discovery, version 13.0.0. SAS 
Campus Drive, Cary, North Carolina	27513, USA.

\noindent Slipke, J.W. 2010. Fishery Analyses and Modeling Simulator (FAMS). Version 1.0.

\noindent Alberta Sustainable Resource Development (ASRD). 2008. 
Electrofishing Certification and Safety Standard. 
Alberta Sustainable Resource Development,	Fish and Wildlife Division. Edmonton, AB. 76 pp.

\noindent Stevens, D.L., A.R.\ Olsen. 2004. 
Spatially balanced sampling of natural resources. 
Journal of the American Statistical Association 99(465):262-278.

\noindent Watkins, O.B., S.C.\ Spencer. 2009. 
Collection, preparation and ageing of walleye otoliths. 
Alberta Sustainable Resource Development, Fish and Wildlife Division. 
Spruce Grove, AB. 26 pp.




\end{document}
# we need a blank line at the end (See Reproducible Research with R and Rstudio, page 247)

